import type { AvailableSensor, SensorGroupColorConfig } from './types';

export const AVAILABLE_SENSORS: AvailableSensor[] = [
  {
    id: 'energy-today',
    label: 'Today',
    value: '12.4',
    unit: 'kWh',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-current',
    label: 'Current',
    value: '2.3',
    unit: 'kW',
    icon: 'activity',
    category: 'energy',
  },
  {
    id: 'energy-bathroom',
    label: 'Bathroom',
    value: '450',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-kitchen',
    label: 'Kitchen',
    value: '1.2',
    unit: 'kW',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-bedroom',
    label: 'Bedroom',
    value: '320',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-living',
    label: 'Living Room',
    value: '890',
    unit: 'W',
    icon: 'zap',
    category: 'energy',
  },
  {
    id: 'energy-week',
    label: 'This Week',
    value: '84.2',
    unit: 'kWh',
    icon: 'trend-up',
    category: 'energy',
  },
  {
    id: 'energy-month',
    label: 'This Month',
    value: '342',
    unit: 'kWh',
    icon: 'trend-up',
    category: 'energy',
  },
  {
    id: 'temp-indoor',
    label: 'Temperature',
    value: '21',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-indoor',
    label: 'Humidity',
    value: '55',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'temp-outdoor',
    label: 'Outdoor Temp',
    value: '18',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-outdoor',
    label: 'Outdoor Humidity',
    value: '72',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'temp-bedroom',
    label: 'Bedroom Temp',
    value: '19',
    unit: '°C',
    icon: 'thermometer',
    category: 'climate',
  },
  {
    id: 'humidity-bedroom',
    label: 'Bedroom Humidity',
    value: '48',
    unit: '%',
    icon: 'droplets',
    category: 'climate',
  },
  {
    id: 'air-quality',
    label: 'Air Quality',
    value: 'Good',
    unit: '',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'wind-speed',
    label: 'Wind Speed',
    value: '12',
    unit: 'km/h',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'uv-index',
    label: 'UV Index',
    value: '5',
    unit: '',
    icon: 'sun',
    category: 'environmental',
  },
  {
    id: 'pressure',
    label: 'Pressure',
    value: '1013',
    unit: 'hPa',
    icon: 'gauge',
    category: 'environmental',
  },
  {
    id: 'co2',
    label: 'CO2 Level',
    value: '420',
    unit: 'ppm',
    icon: 'wind',
    category: 'environmental',
  },
  {
    id: 'noise-level',
    label: 'Noise Level',
    value: '42',
    unit: 'dB',
    icon: 'activity',
    category: 'other',
  },
  {
    id: 'light-level',
    label: 'Light Level',
    value: '450',
    unit: 'lux',
    icon: 'sun',
    category: 'other',
  },
];

export const SENSOR_GROUP_COLOR_MAP: Record<
  'teal' | 'blue' | 'purple' | 'amber' | 'emerald',
  SensorGroupColorConfig
> = {
  teal: {
    iconBg: 'bg-teal-500/20',
    iconColor: 'text-teal-400',
    hover: 'hover:bg-teal-500/10',
    selected: 'bg-teal-500/20 border-teal-500/40',
  },
  blue: {
    iconBg: 'bg-blue-500/20',
    iconColor: 'text-blue-400',
    hover: 'hover:bg-blue-500/10',
    selected: 'bg-blue-500/20 border-blue-500/40',
  },
  purple: {
    iconBg: 'bg-purple-500/20',
    iconColor: 'text-purple-400',
    hover: 'hover:bg-purple-500/10',
    selected: 'bg-purple-500/20 border-purple-500/40',
  },
  amber: {
    iconBg: 'bg-amber-500/20',
    iconColor: 'text-amber-400',
    hover: 'hover:bg-amber-500/10',
    selected: 'bg-amber-500/20 border-amber-500/40',
  },
  emerald: {
    iconBg: 'bg-emerald-500/20',
    iconColor: 'text-emerald-400',
    hover: 'hover:bg-emerald-500/10',
    selected: 'bg-emerald-500/20 border-emerald-500/40',
  },
};
