export {
  mapCalendarSources,
  mapCameraDevice,
  mapClimateDevice,
  mapCoverDevice,
  mapFanDevice,
  mapLightDevice,
  mapLockDevice,
  mapMediaDevice,
  mapPersonDevice,
  mapSceneDevice,
  mapSensorDevice,
  mapSwitchDevice,
  mapVacuumDevice,
  mapWeatherDevice,
} from '@/app/hooks/device-mappers';
