export const STORAGE_KEYS = {
  authConfig: 'ha_auth_config',
  haConfig: 'ha-dashboard-config',
  cardSizes: 'ha-dashboard-card-sizes',
  mediaSectionCardSizes: 'ha-dashboard-media-section-card-sizes',
  cardOrders: 'ha-dashboard-card-orders',
  roomOrder: 'ha-dashboard-room-order',
  allViewGrouping: 'ha-dashboard-all-view-grouping',
  switchCardMetricPreferences: 'ha-dashboard-switch-card-metrics',
  switchCardIcons: 'ha-dashboard-switch-card-icons',
  switchCardTintColors: 'ha-dashboard-switch-card-tint-colors',
  calendarCardSources: 'ha-dashboard-calendar-card-sources',
  calendarCardViewModes: 'ha-dashboard-calendar-card-view-modes',
  calendarCardTintColors: 'ha-dashboard-calendar-card-tint-colors',
  weatherCardTintColors: 'ha-dashboard-weather-card-tint-colors',
  rssFeedProviders: 'ha-dashboard-rss-feed-providers',
  rssCardProviders: 'ha-dashboard-rss-card-providers',
  rssCardArticleCount: 'ha-dashboard-rss-card-article-count',
  lightMemoryState: 'ha-dashboard-light-memory-state',
  cardZones: 'ha-dashboard-card-zones',
  homeDashboardLayout: 'ha-dashboard-home-layout',
  dashboardProfileSync: 'navet-dashboard-profile-sync',
} as const;
