export const STORAGE_KEYS = {
  authConfig: 'ha_auth_config',
  haConfig: 'ha-dashboard-config',
  cardSizes: 'ha-dashboard-card-sizes',
  cardOrders: 'ha-dashboard-card-orders',
  roomOrder: 'ha-dashboard-room-order',
  allViewGrouping: 'ha-dashboard-all-view-grouping',
  switchCardMetricPreferences: 'ha-dashboard-switch-card-metrics',
  calendarCardSources: 'ha-dashboard-calendar-card-sources',
  calendarCardViewModes: 'ha-dashboard-calendar-card-view-modes',
  rssFeedProviders: 'ha-dashboard-rss-feed-providers',
  rssCardProviders: 'ha-dashboard-rss-card-providers',
  rssCardArticleCount: 'ha-dashboard-rss-card-article-count',
  lightMemoryState: 'ha-dashboard-light-memory-state',
  cardZones: 'ha-dashboard-card-zones',
} as const;
