services:
  navet:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      NAVET_HASS_URL: ${NAVET_HASS_URL}
      NAVET_HASS_TOKEN: ${NAVET_HASS_TOKEN}
    ports:
      - "8080:80"
    restart: unless-stopped
