import { runProviderPackageRegistrationTests } from '@navet/core/provider-package-test-suite';
import { vi } from 'vitest';
import { createHomeAssistantProviderPackageRegistration } from './homeassistant-provider-registration';

runProviderPackageRegistrationTests({
  providerName: 'Home Assistant',
  providerId: 'home_assistant',
  createRegistration: () =>
    createHomeAssistantProviderPackageRegistration({
      getSession: () => null,
      bridge: {
        callService: vi.fn(async () => undefined),
        signPath: vi.fn(async (path: string) => ({ path })),
        getCameraStreamUrl: vi.fn(async () => ({ url: '/stream' })),
        getCameraStreamPaths: vi.fn(async () => ({})),
        addListener: vi.fn(() => () => {}),
        isConnected: () => false,
        getPanelHass: () => null,
        getConnection: () => null,
        getEntities: () => null,
        getEntityRegistry: () => [],
        getConfig: () => null,
        updateLight: vi.fn(async () => undefined),
        playMedia: vi.fn(async () => undefined),
        browseMediaPlayer: vi.fn(async () => ({ title: 'Media' })),
        searchMediaPlayer: vi.fn(async () => ({ title: 'Media' })),
        selectMediaPlayerSource: vi.fn(async () => undefined),
        selectMediaPlayerSoundMode: vi.fn(async () => undefined),
        seekMediaPlayer: vi.fn(async () => undefined),
        clearMediaPlayerPlaylist: vi.fn(async () => undefined),
        updateMediaPlayerPower: vi.fn(async () => undefined),
        sendRemoteCommand: vi.fn(async () => undefined),
        browseMediaSource: vi.fn(async () => ({ title: 'Media' })),
        resolveMediaSource: vi.fn(async () => ({ url: '/media' })),
        getAutomationConfig: vi.fn(async () => ({ config: {} })),
        getCameraCapabilities: vi.fn(async () => ({})),
        enableCameraMotionDetection: vi.fn(async () => undefined),
        disableCameraMotionDetection: vi.fn(async () => undefined),
        getWebRtcClientConfiguration: vi.fn(async () => ({})),
        subscribeCameraWebRtcOffer: vi.fn(async () => () => {}),
        addCameraWebRtcCandidate: vi.fn(async () => undefined),
        createArea: vi.fn(async (name: string) => ({ area_id: name, name })),
        updateEntityArea: vi.fn(async () => undefined),
        updateEntityName: vi.fn(async () => undefined),
        deleteArea: vi.fn(async () => undefined),
        resolveArtwork: vi.fn(async () => ({
          id: 'artwork',
          kind: 'unavailable' as const,
          cacheKey: 'artwork',
          authStrategy: 'none' as const,
        })),
        resolveProxyUrl: vi.fn((resourceUrl: string) => resourceUrl),
        getCameraPlaybackPlan: vi.fn(async () => ({ mode: 'snapshot' })),
        resolveCameraStreamResource: vi.fn(async () => ({
          id: 'camera',
          kind: 'unavailable' as const,
          cacheKey: 'camera',
          authStrategy: 'none' as const,
        })),
        getStoreState: () => ({
          connected: false,
          config: null,
          entities: null,
          areas: [],
          deviceRegistry: [],
          entityRegistry: [],
          connect: vi.fn(async () => undefined),
          disconnect: vi.fn(async () => undefined),
          syncPanelHass: vi.fn(),
        }),
        subscribeStore: vi.fn(() => () => {}),
      },
    }),
  expectedStatus: 'implemented',
  supportedFeatures: ['rooms', 'lighting', 'mediaControls', 'cameraStreams', 'notifications'],
});
