export const STORAGE_KEYS = {
  cardSizes: 'navet-card-sizes',
  mediaSectionCardSizes: 'navet-media-section-card-sizes',
  cardOrders: 'navet-card-orders',
  roomOrder: 'navet-room-order',
  hiddenRooms: 'navet-hidden-rooms',
  allViewGrouping: 'navet-all-view-grouping',
  switchCardMetricPreferences: 'navet-switch-card-metrics',
  switchCardIcons: 'navet-switch-card-icons',
  switchCardTintColors: 'navet-switch-card-tint-colors',
  sensorCardIcons: 'navet-sensor-card-icons',
  calendarCardSources: 'navet-calendar-card-sources',
  calendarCardViewModes: 'navet-calendar-card-view-modes',
  calendarCardTintColors: 'navet-calendar-card-tint-colors',
  weatherCardTintColors: 'navet-weather-card-tint-colors',
  rssFeedProviders: 'navet-rss-feed-providers',
  rssCardProviders: 'navet-rss-card-providers',
  rssCardArticleCount: 'navet-rss-card-article-count',
  lightMemoryState: 'navet-light-memory-state',
  cardZones: 'navet-card-zones',
  homeDashboardLayout: 'navet-home-layout',
  dashboardProfileSync: 'navet-dashboard-profile-sync',
} as const;

export const LEGACY_STORAGE_KEYS = {
  cardSizes: 'ha-dashboard-card-sizes',
  mediaSectionCardSizes: 'ha-dashboard-media-section-card-sizes',
  cardOrders: 'ha-dashboard-card-orders',
  roomOrder: 'ha-dashboard-room-order',
  hiddenRooms: 'ha-dashboard-hidden-rooms',
  allViewGrouping: 'ha-dashboard-all-view-grouping',
  switchCardMetricPreferences: 'ha-dashboard-switch-card-metrics',
  switchCardIcons: 'ha-dashboard-switch-card-icons',
  switchCardTintColors: 'ha-dashboard-switch-card-tint-colors',
  sensorCardIcons: 'ha-dashboard-sensor-card-icons',
  calendarCardSources: 'ha-dashboard-calendar-card-sources',
  calendarCardViewModes: 'ha-dashboard-calendar-card-view-modes',
  calendarCardTintColors: 'ha-dashboard-calendar-card-tint-colors',
  weatherCardTintColors: 'ha-dashboard-weather-card-tint-colors',
  rssFeedProviders: 'ha-dashboard-rss-feed-providers',
  rssCardProviders: 'ha-dashboard-rss-card-providers',
  rssCardArticleCount: 'ha-dashboard-rss-card-article-count',
  lightMemoryState: 'ha-dashboard-light-memory-state',
  cardZones: 'ha-dashboard-card-zones',
  homeDashboardLayout: 'ha-dashboard-home-layout',
} as const;

export const STORE_STORAGE_KEYS = {
  settings: 'navet-settings',
  theme: 'navet-theme',
  navigation: 'navet-navigation',
  editMode: 'navet-edit-mode',
  customCards: 'navet-custom-cards',
  lightPresetSettings: 'navet-light-preset-settings',
} as const;

export const LEGACY_STORE_STORAGE_KEYS = {
  settings: 'ha-dashboard-settings',
  theme: 'ha-dashboard-theme',
  navigation: 'ha-dashboard-navigation',
  editMode: 'ha-dashboard-edit-mode',
  customCards: 'ha-dashboard-custom-cards',
  lightPresetSettings: 'ha-dashboard-light-preset-settings',
} as const;
